Documenation: Adding instruction for local windows install
TAS-scorchedshadow/training-program-exercises pull request #21
Opened 2024-09-01 06:56 UTC by TAS-scorchedshadow

2024-09-01 07:52 UTC, JeydinNewWon commented
Dylan resist the urge to yap about tech stack challenge!!!!

2024-09-03 01:13 UTC, JeydinNewWon requested changes
I think is guide is very good overall, imo - just some minor tidbits - 

- I would (yes unironically) recommend putting some emojis next to the headers to help visually distinguish between MacOS, Windows, Linux systems in `installation.md`. 
- Perhaps we could separate the Git and Node installations into separate markdown files? - Having them in one `README.md` is a bit confusing

2024-09-12 11:47 UTC, TAS-scorchedshadow commented
- Updated SSH Key Reference
- I think the readability is alright without emojis but I can add if you think its really needed
- When I tried splitting git/node but it seemed a bit unnecessary/clunky but lmk if you find a nice way of doing it

2024-09-12 11:49 UTC, JeydinNewWon approved these changes

2024-09-12 11:56 UTC, merged